const nodeBin = "/root/.nvm/versions/node/v20.20.2/bin";

module.exports = {
  apps: [
    {
      name: "yolo-web",
      cwd: "/root/yolomarkets/web",
      script: "npm",
      // Dev mode (hot reload). Heavier on RAM than `run start` — a swap file is
      // configured so its ~2 GB footprint can't OOM-kill the rest of the stack.
      args: "run dev",
      interpreter: "none",
      out_file: "/root/yolomarkets/logs/yolo-web-out.log",
      error_file: "/root/yolomarkets/logs/yolo-web-error.log",
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      env: {
        PATH: `${nodeBin}:${process.env.PATH}`,
        NODE_ENV: "development",
        PORT: "3000",
      },
    },
    {
      name: "yolo-catalog-indexer",
      cwd: "/root/yolomarkets/web",
      script: "npm",
      args: "run markets:catalog:indexer",
      interpreter: "none",
      out_file: "/root/yolomarkets/logs/yolo-catalog-indexer-out.log",
      error_file: "/root/yolomarkets/logs/yolo-catalog-indexer-error.log",
      autorestart: true,
      max_restarts: 20,
      restart_delay: 30000,
      env: {
        PATH: `${nodeBin}:${process.env.PATH}`,
        NODE_ENV: "production",
        CATALOG_INDEXER_POLL_SECONDS: "20",
      },
    },
    {
      name: "yolo-fast-markets",
      cwd: "/root/yolomarkets/web",
      script: "npm",
      args: "run markets:fast:keeper",
      interpreter: "none",
      out_file: "/root/yolomarkets/logs/yolo-fast-markets-out.log",
      error_file: "/root/yolomarkets/logs/yolo-fast-markets-error.log",
      autorestart: true,
      max_restarts: 20,
      restart_delay: 30000,
      env: {
        PATH: `${nodeBin}:${process.env.PATH}`,
        NODE_ENV: "production",
        FAST_MARKET_POLL_SECONDS: "30",
      },
    },
    {
      name: "yolo-polymarket-resolver",
      cwd: "/root/yolomarkets/web",
      script: "npm",
      args: "run markets:poly:resolver",
      interpreter: "none",
      out_file: "/root/yolomarkets/logs/yolo-polymarket-resolver-out.log",
      error_file: "/root/yolomarkets/logs/yolo-polymarket-resolver-error.log",
      autorestart: true,
      max_restarts: 20,
      restart_delay: 30000,
      env: {
        PATH: `${nodeBin}:${process.env.PATH}`,
        NODE_ENV: "production",
        POLYMARKET_RESOLUTION_POLL_SECONDS: "300",
      },
    },
    {
      name: "yolo-fast-swarm",
      cwd: "/root/yolomarkets/web",
      script: "npm",
      args: "run markets:fast:swarm",
      interpreter: "none",
      out_file: "/root/yolomarkets/logs/yolo-fast-swarm-out.log",
      error_file: "/root/yolomarkets/logs/yolo-fast-swarm-error.log",
      autorestart: true,
      max_restarts: 20,
      restart_delay: 30000,
      env: {
        PATH: `${nodeBin}:${process.env.PATH}`,
        NODE_ENV: "production",
        FAST_SWARM_LIVE: "1",
        FAST_SWARM_POLL_SECONDS: "20",
      },
    },
    {
      name: "yolo-agent",
      cwd: "/root/yolomarkets/agent",
      script: "/root/.local/bin/uv",
      args: "run python runner.py --port 8080",
      interpreter: "none",
      out_file: "/root/yolomarkets/logs/yolo-agent-out.log",
      error_file: "/root/yolomarkets/logs/yolo-agent-error.log",
      autorestart: true,
      max_restarts: 20,
      restart_delay: 30000,
      env: {
        PATH: `${nodeBin}:/root/.local/bin:${process.env.PATH}`,
        PORT: "8080",
        PYTHONUNBUFFERED: "1",
        RUNNER_LIVE: "1",
        RUNNER_INTERVAL_SECONDS: "180",
        RUNNER_MAX_CONSECUTIVE_FAILURES: "5",
      },
    },
  ],
};
